---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install storage components
  hosts: oo_first_master
  gather_facts: no
  tags:
    - storage
  roles:
    - storage
