- name: Add Service Account
  block:
    - oc_serviceaccount:
        state: present
        name: image-pruner
        namespace: "{{ getupcloud_namespace }}"
        secrets:
          - image-pruner

- name: Assign role to Service Account
  oc_adm_policy_user:
    state: present
    user: "system:serviceaccount:{{ getupcloud_namespace }}:image-pruner"
    namespace: "{{ getupcloud_namespace }}"
    resource_kind: cluster-role
    resource_name: cluster-admin

- name: Add template
  template:
    src: imagepruner.j2
    dest: "imagepruner.yml"

- name: Create CronJob for image pruner
  oc_obj:
    state: present
    namespace: "{{ getupcloud_namespace }}"
    kind: CronJob
    name: image-pruner
    files:
      - "imagepruner.yml"
    delete_after: yes
