#!/bin/bash

set -eu

if [ -e .suffix ]; then
    IMAGE_SUFFIX=$(<.suffix)
fi

if [ -v IMAGE_SUFFIX ]; then
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
fi

if [ ! -v RELEASE ] && [ -d .git ]; then
    RELEASE=$(git log --pretty=format:"%h" -n 1)
else
    RELEASE=devel
fi

image=getup-engine${IMAGE_SUFFIX}:${1}
dockerfile=Dockerfile-${1}
shift

echo "---> Building $image from $dockerfile"
set -x 2>/dev/null
sudo docker build . -t $image -f $dockerfile --build-arg RELEASE=$RELEASE $@
