#!/bin/bash

export INSTALLER_VERSION=$1
source prepare-image $INSTALLER_VERSION

set -eu

echo "---> Building $image_name from $dockerfile"
set -x 2>/dev/null
sudo docker build . -t $image_name -f $dockerfile --build-arg RELEASE=$INSTALLER_RELEASE
