---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Prometheus/Grafana Monitoring
  hosts: oo_first_master
  gather_facts: no
  tags:
    - getup-monitoring
    - prometheus
  tasks:
    - include_role:
        name: getup-prometheus
    - include_role:
        name: getup-alertmanager-check-config

- name: EventRouter
  hosts: oo_first_master
  gather_facts: no
  tags:
    - getup-monitoring
    - eventrouter
  tasks:
    - include_role:
        name: getup-eventrouter

- name: Kubestate
  hosts: oo_first_master
  gather_facts: no
  tags:
    - getup-monitoring
    - kubestate
  tasks:
    - include_role:
        name: getup-kubestate

- name: Alertmanager Zabbix Webhook
  hosts: oo_first_master
  gather_facts: no
  tags:
    - getup-monitoring
    - zabbix
  tasks:
    - include_role:
        name: getup-zabbix
      when: getupcloud_install_alertmanager_zabbix_webhook | default(false) | bool

- name: Zabbix-Agent
  hosts: oo_first_master
  gather_facts: no
  tags:
    - getup-monitoring
    - zabbix
  tasks:
    - include_role:
        name: getup-zabbix-agent
      when: getupcloud_zabbix_agent | default(false) | bool

