---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- import_playbook: ../tools/config.yml

- import_playbook: ../monitoring/config.yml

- import_playbook: ../storage/config.yml
  when: storageclass_name is defined and storageclass_name != ""
