---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init
    
- name: Copy tools
  hosts: oo_first_master
  tags:
    - tools
  tasks:
    - name: Copy cluster-metrics
      copy:
        src: ../../../bin/cluster-metrics
        dest: /usr/local/bin/cluster-metrics
        mode: 0755
    - name: Copy sh profiles
      copy:
        src: ../../../bin/on.sh
        dest: /etc/profile.d/on.sh
        mode: 0644

- import_playbook: ../monitoring/config.yml

- import_playbook: ../storage/config.yml
  when: storageclass_name is defined and storageclass_name != ""
