- name: RBAC | Add template
  template:
    src: rbac.yaml.j2
    dest: "rbac.yaml"
    
- name: EventRouter Create Cluster Role
  oc_obj:
    state: present
    namespace: "{{ openshift_prometheus_namespace  }}"
    kind: ClusterRole
    name: eventrouter-exporter
    files:
      - "rbac.yaml"
    delete_after: yes

- name: Assign role to Service Account
  oc_adm_policy_user:
    state: present
    user: "system:serviceaccount:{{ openshift_prometheus_namespace }}:eventrouter-exporter"
    namespace: "{{ openshift_prometheus_namespace  }}"
    resource_kind: cluster-role
    resource_name: eventrouter-exporter

- name: EventRouter | Copy objects
  template:
    src: eventrouter.yml.j2
    dest: "eventrouter.yml"
  
- name: Create EventRouter objects
  shell: "{{ oc }} apply -f eventrouter.yml -n {{ openshift_prometheus_namespace }}"
