---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Open ports
  hosts: oo_first_master
  gather_facts: no
  tags:
    - firewall
  roles:
    - firewall