---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install lambda prom
  hosts: oo_first_master
  gather_facts: no
  tags:
    - lambda-prom
  roles:
    - lambda-prom