---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install Billing
  hosts: masters
  tags:
    - getup-usage
  roles:
    - getup-usage
