---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install Backup
  hosts: oo_first_master
  tags:
    - getup-backup
  tasks:
  - include_role:
      name: getup-backup
