---
# user databases backup
- name: Delete old database-backup cronjob
  command: |
    {{ oc }} delete --ignore-not-found cronjobs/database-backup -n "{{ getupcloud_namespace }}"

- name: Create database-backup cronjob
  command: |
    oc run database-backup
    -n "{{ getupcloud_namespace }}"
    --env 'AWS_ACCESS_KEY_ID={{ getupcloud_backup_storage_s3_accesskey | default("") }}'
    --env 'AWS_SECRET_ACCESS_KEY={{ getupcloud_backup_storage_s3_secretkey | default("") }}'
    --env 'AWS_REGION={{ getupcloud_backup_storage_s3_region | default("") }}'
    --env 'AWS_S3_BUCKET_NAME={{ getupcloud_backup_storage_s3_bucket | default("") }}'
    --env 'NAMESPACE={{ getupcloud_namespace }}'
    --image 'getupcloud/database-backup:latest'
    --schedule '20 5 * * *'
    --restart Never
    --labels 'job=database-backup,provider=aws,storage_type={{ getupcloud_backup_storage_kind }}'

# volume backup
- name: Delete old volume-backup cronjob
  command: |
    {{ oc }} delete --ignore-not-found cronjobs/volume-backup -n "{{ getupcloud_namespace }}"

- name: Create AWS EBS backup cronjob
  command: |
    {{ oc }} run volume-backup
    -n "{{ getupcloud_namespace }}"
    --env 'AWS_ACCESS_KEY_ID={{ getupcloud_backup_storage_s3_accesskey | default("") }}'
    --env 'AWS_SECRET_ACCESS_KEY={{ getupcloud_backup_storage_s3_secretkey | default("") }}'
    --env 'AWS_DEFAULT_REGION={{ getupcloud_backup_storage_s3_region | default("") }}'
    --env 'DEFAULT_RETENTION_DAYS={{ getupcloud_backup_retention_days | default(7) | int }}'
    --image getupcloud/volume-backup:latest
    --schedule '20 4 * * *'
    --restart Never
    --labels 'job=volume-backup,provider=aws,storage_type={{ getupcloud_backup_storage_kind }}'

# etcd backup
- name: Install dependencies
  pip:
    name: awscli

- name: Create etcd backup crontab
  cron:
    name: "Backup etcd data"
    user: "root"
    special_time: hourly
    job: >
      AWS_ACCESS_KEY_ID={{ getupcloud_backup_storage_s3_accesskey }}
      AWS_SECRET_ACCESS_KEY={{ getupcloud_backup_storage_s3_secretkey }}
      AWS_DEFAULT_REGION={{ getupcloud_backup_storage_s3_region }}
      AWS_S3_BUCKET_NAME={{ getupcloud_backup_storage_s3_bucket }}
      {{ getupcloud_backup_install_dir }}/etcd-backup {{ openshift_cloudprovider_kind }}
