---
- import_tasks: aws.yml
  when:
    - openshift_cloudprovider_kind is defined and openshift_cloudprovider_kind == "aws"

- import_tasks: azure.yml
  when:
    - openshift_cloudprovider_kind is defined and openshift_cloudprovider_kind == "azure"

- import_tasks: gce.yml
  when:
    - openshift_cloudprovider_kind is defined and openshift_cloudprovider_kind == "gce"
