---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install Billing
  hosts: oo_first_master
  tags:
    - getup-billing
  tasks:
    - include_role:
        name: getup-billing
