- name: Kubestate | Add template
  template:
    src: kubestate.yaml.j2
    dest: "kubestate.yaml"

- name: RBAC | Add template
  template:
    src: rbac.yaml.j2
    dest: "rbac.yaml"
    
- name: kubestate Create Cluster Role
  oc_obj:
    state: present
    namespace: "{{ openshift_prometheus_namespace  }}"
    kind: ClusterRole
    name: kubestate-exporter
    files:
      - "rbac.yaml"
    delete_after: yes
  ignore_errors: yes
    
- name: Assign role to Service Account
  oc_adm_policy_user:
    state: present
    user: "system:serviceaccount:{{ openshift_prometheus_namespace }}:kubestate-exporter"
    namespace: "{{ openshift_prometheus_namespace  }}"
    resource_kind: cluster-role
    resource_name: cluster-admin

- name: create template
  oc_obj:
    name: kubestate-exporter
    state: present
    namespace: "{{ openshift_prometheus_namespace }}"
    kind: template
    files:
    - kubestate.yaml
  ignore_errors: yes

- name: kubestate | Create Resources kubestate
  oc_process:
    namespace: "{{ openshift_prometheus_namespace }}"
    template_name: kubestate-exporter
    create: True


  
  
  
