---
- name: Create temp directory
  command: mktemp -d /tmp/getupcloud-billing-XXXXXX
  register: tmp_dir
  changed_when: False
  check_mode: no

- name: Copy deploy key
  copy:
    src: "{{ getupcloud_billing_repository_key_file }}"
    dest: "{{ tmp_dir.stdout }}/id_rsa"
    mode: 0600

- name: Clone getup-usage repo
  git:
    repo: "{{ getupcloud_billing_repository }}"
    version: "{{ getupcloud_billing_repository_branch }}"
    key_file: "{{ tmp_dir.stdout }}/id_rsa"
    accept_hostkey: yes
    clone: yes
    dest: "{{ tmp_dir.stdout }}/getup-usage"

- debug:
    msg: "Cloned getup-usage to {{ tmp_dir.stdout }}/getup-usage"

- name: Install getup-usage collector
  git:
    repo: "{{ tmp_dir.stdout }}/getup-usage"
    version: "{{ getupcloud_billing_repository_branch }}"
    clone: yes
    dest: "{{ getupcloud_billing_install_dir }}"

- name: Install dependencies
  block:
  - yum:
      state: present
      name:
        - gcc
        - mysql-devel
        - python-devel
        - python-setuptools

  - name: Install virtualenv
    command: easy_install virtualenv

  - name: Install pip
    command: easy_install pip

  - name: Check virtualenv
    stat:
      path: "{{ getupcloud_billing_install_dir }}/.env"
    register: env_dir

  - name: Init virtualenv
    shell: >
      virtualenv .env &&
      source .env/bin/activate &&
      pip install -r requirements.txt
    args:
      chdir: "{{ getupcloud_billing_install_dir }}/collector"
    when: env_dir.stat.exists == False

- name: Create service account
  oc_serviceaccount:
    name: usage-collector
    state: present
    namespace: "{{ getupcloud_namespace }}"

- name: Add cluster role to user
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ getupcloud_namespace }}:usage-collector"
    resource_kind: cluster-role
    resource_name: cluster-reader
    state: present

- name: Create log dir
  file:
    path: /var/log/getup-usage
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0750

- name: Migrate usage database
  shell: ./pull-metrics migrate_db
  args:
    chdir: "{{ getupcloud_billing_install_dir }}/collector"

- name: Create usage crontab
  cron:
    name: "Pull usage metrics"
    user: "{{ ansible_user }}"
    job: >
      OPENSHIFT_MASTER_URL=https://{{ openshift_master_cluster_hostname }}
      BILLING_NAMESPACE={{ getupcloud_namespace }}
      SERVICE_ACCOUNT=usage-collector
      {{ getupcloud_billing_install_dir }}/collector/pull-metrics > /var/log/getup-billing/pull-metrics.log

- name: Create partials and trial control crontab
  cron:
    name: "Run partials and trial control"
    user: "{{ ansible_user }}"
    minute: 0
    hour: 0
    job: >
      OPENSHIFT_MASTER_URL=https://{{ openshift_master_cluster_hostname }}
      BILLING_NAMESPACE={{ getupcloud_namespace }}
      SERVICE_ACCOUNT=usage-collector
      {{ getupcloud_billing_install_dir }}/collector/make-partials > /var/log/getup-billing/make-partials.log
