---
- name: Setup
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
    - always
  roles:
    - init

- name: Install Getup Image Pruner
  hosts: oo_first_master
  tags:
    - getup-imagepruner
  tasks:
    - include_role:
        name: getup-imagepruner
