#!/bin/bash

set -eu

if [ -x $GETUPENGINE_ROOT/installer/$FLAVOR/deploy ]; then
    exec $GETUPENGINE_ROOT/installer/$FLAVOR/deploy $@

elif [ which deploy-$flavor 2>/dev/null ]; then
    exec deploy-$flavor $@
fi
